<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Eye } from 'lucide-vue-next'
import { http } from '@/shared/api/httpClient'
const items=ref<any[]>([]),total=ref(0),page=ref(1),loading=ref(false),selected=ref<any|null>(null);const pageSize=50
const filters=ref({modulo:'',accion:'',buscar:'',desde:'',hasta:''})
async function load(reset=false){if(reset)page.value=1;loading.value=true;try{const{data}=await http.get('/auditoria',{params:{...filters.value,page:page.value,pageSize}});items.value=data.items;total.value=data.total}finally{loading.value=false}}
function details(item:any){try{return Object.entries(JSON.parse(item.detalleJson))as[string,any][]}catch{return[]}}
function value(v:unknown){if(v===null||v===undefined||v==='')return'—';if(typeof v==='boolean')return v?'Sí':'No';return String(v)}
function dateTime(v:string){return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'medium'}).format(new Date(v))}
onMounted(()=>load())
</script>
<template><section class="page"><div class="page-title"><div><h2>Registro de auditoría</h2><p>Historial de las operaciones realizadas por los usuarios.</p></div></div><form class="audit-filters panel" @submit.prevent="load(true)"><div class="field"><label>Vista o módulo</label><select v-model="filters.modulo"><option value="">Todos</option><option>Ventas</option><option>Cuotas</option><option>Caja</option><option>Clientes</option><option>Usuarios</option><option>Administración</option></select></div><div class="field"><label>Acción</label><select v-model="filters.accion"><option value="">Todas</option><option>Creación</option><option>Modificación</option><option>Eliminación</option></select></div><div class="field"><label>Desde</label><input v-model="filters.desde" type="date"></div><div class="field"><label>Hasta</label><input v-model="filters.hasta" type="date"></div><div class="field audit-search"><label>Usuario, venta o movimiento</label><input v-model="filters.buscar" placeholder="Buscar usuario, ID o cambio"></div><button class="btn">Filtrar</button></form><div class="panel"><div class="panel-head"><h3>{{total}} movimientos registrados</h3></div><div v-if="loading" class="loading">Cargando auditoría…</div><table v-else><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Vista</th><th>Acción</th><th>Registro afectado</th><th>Cambios</th></tr></thead><tbody><tr v-for="x in items" :key="x.id"><td>{{dateTime(x.fechaHora)}}</td><td><b>{{x.usuario}}</b></td><td>{{x.modulo}}</td><td><span class="badge" :class="{warn:x.accion==='Eliminación'}">{{x.accion}}</span></td><td>{{x.entidad}}<small class="entity-id">{{x.entidadId}}</small></td><td><button class="icon-btn" title="Ver cambios" @click="selected=x"><Eye/></button></td></tr><tr v-if="!items.length"><td colspan="6" class="empty">No hay registros para los filtros elegidos.</td></tr></tbody></table><div class="audit-pages"><button class="btn secondary compact" :disabled="page===1" @click="page--;load()">Anterior</button><span>Página {{page}}</span><button class="btn secondary compact" :disabled="page*pageSize>=total" @click="page++;load()">Siguiente</button></div></div><div v-if="selected" class="modal-bg" @click.self="selected=null"><div class="modal"><h3>Cambios realizados</h3><p><b>{{selected.usuario}}</b> · {{dateTime(selected.fechaHora)}} · {{selected.entidad}}</p><table class="changes"><thead><tr><th>Campo</th><th>Valor anterior</th><th>Valor nuevo</th></tr></thead><tbody><tr v-for="[field,change] in details(selected)" :key="field"><td><b>{{field}}</b></td><td>{{value(change.anterior)}}</td><td>{{value(change.nuevo)}}</td></tr></tbody></table><div class="actions"><button class="btn secondary" @click="selected=null">Cerrar</button></div></div></div></section></template>
