<script setup lang="ts">
import{ref,onMounted}from'vue';import{http}from'@/shared/api/httpClient'
const data=ref<any>({saldo:0,movimientos:[]}),show=ref(false),error=ref('')
const form=ref({tipo:'Ingreso',monto:0,concepto:'',usuario:'Administrador'})
const money=(v:number)=>v.toLocaleString('es-AR',{style:'currency',currency:'ARS'})
async function load(){data.value=(await http.get('/caja')).data}
function openForm(tipo:'Ingreso'|'Retiro'){form.value={tipo,monto:0,concepto:'',usuario:'Administrador'};error.value='';show.value=true}
async function save(){try{await http.post('/caja/movimientos',form.value);show.value=false;await load()}catch(e:any){error.value=e.response?.data?.detail??e.response?.data?.title??'No se pudo registrar el movimiento.'}}
onMounted(load)
</script>
<template><section class="page"><div class="page-title"><div><h2>Caja</h2><p>Ingresos y retiros trazables.</p></div><div class="row-actions"><button class="btn" @click="openForm('Ingreso')">+ Ingresar dinero</button><button class="btn danger-btn" @click="openForm('Retiro')">− Retirar dinero</button></div></div><div class="grid"><article class="card metric"><small>Saldo actual</small><strong>{{money(data.saldo)}}</strong><em>Calculado desde el historial</em></article></div><div class="panel"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Observación</th><th>Usuario</th><th>Monto</th></tr></thead><tbody><tr v-for="m in data.movimientos" :key="m.id"><td>{{new Date(m.fecha).toLocaleString('es-AR')}}</td><td><span class="badge" :class="{warn:m.tipo==='Retiro'}">{{m.tipo}}</span></td><td>{{m.concepto}}</td><td>{{m.usuario}}</td><td><b :class="{negative:m.tipo==='Retiro'}">{{m.tipo==='Retiro'?'− ':'+ '}}{{money(m.monto)}}</b></td></tr></tbody></table><div v-if="!data.movimientos.length" class="empty">No hay movimientos todavía.</div></div><div v-if="show" class="modal-bg"><form class="modal small-modal" @submit.prevent="save"><h3>{{form.tipo==='Ingreso'?'Ingresar dinero':'Retirar dinero'}}</h3><p>Este movimiento quedará registrado en el historial de caja.</p><p v-if="error" class="error">{{error}}</p><div class="field"><label>Monto</label><input v-model.number="form.monto" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Observación / motivo</label><textarea v-model="form.concepto" maxlength="500" rows="4" placeholder="Ej.: compra de insumos, aporte de capital..." required></textarea></div><div class="actions"><button type="button" class="btn secondary" @click="show=false">Cancelar</button><button class="btn" :class="{'danger-btn':form.tipo==='Retiro'}">Confirmar {{form.tipo.toLowerCase()}}</button></div></form></div></section></template>
