<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Pencil, Trash2 } from 'lucide-vue-next'
import { http, apiErrorMessage } from '@/shared/api/httpClient'
import { confirmAction, notify } from '@/shared/uiFeedback'
import GeografiaAutocomplete from '@/shared/components/GeografiaAutocomplete.vue'
import { pluralize } from '@/shared/formatters'
interface GeoOption{id:string;nombre:string}
const items=ref<any[]>([]),show=ref(false),error=ref(''),editingId=ref<string|null>(null),buscar=ref(''),page=ref(1),total=ref(0),totalPages=ref(0),loading=ref(false),loadError=ref('')
const provincias=ref<GeoOption[]>([]),localidades=ref<GeoOption[]>([]),geoAvailable=ref(false),geoMode=ref(false),geoLoading=ref(false),geoNotice=ref('')
const fields=[{key:'nombre',label:'Nombre',type:'text'},{key:'apellido',label:'Apellido',type:'text'},{key:'telefono',label:'Teléfono',type:'tel'},{key:'correo',label:'Correo electrónico',type:'email'}] as const
const blank=()=>({nombre:'',apellido:'',telefono:'',correo:'',localidad:'',provincia:'',localidadId:'',provinciaId:'',tipo:'Particular',fechaPrimerContacto:new Date().toISOString().slice(0,10),observaciones:''})
const form=ref(blank())
async function load(reset=false){if(reset)page.value=1;loading.value=true;loadError.value='';try{const{data}=await http.get('/clientes',{params:{page:page.value,pageSize:20,buscar:buscar.value.trim()||undefined}});items.value=data.items;total.value=Number(data.totalCount??data.total??data.items?.length??0);totalPages.value=Number(data.totalPages??1)}catch(e:any){loadError.value=apiErrorMessage(e,'No se pudieron cargar los clientes.')}finally{loading.value=false}}
function changePage(value:number){page.value=value;load()}
async function loadProvincias(){try{provincias.value=(await http.get('/geografia/provincias')).data;geoAvailable.value=true}catch{geoAvailable.value=false;geoNotice.value='No se pudo consultar Georef. Podés cargar provincia y localidad manualmente.'}}
async function loadLocalidades(){localidades.value=[];if(!form.value.provinciaId)return;geoLoading.value=true;try{localidades.value=(await http.get('/geografia/localidades',{params:{provincia:form.value.provinciaId}})).data}catch{geoNotice.value='Georef no respondió. Se habilitó la carga manual para no bloquear el formulario.';geoMode.value=false;form.value.provinciaId='';form.value.localidadId=''}finally{geoLoading.value=false}}
function create(){editingId.value=null;form.value=blank();error.value='';geoNotice.value=geoAvailable.value?'':'Georef no está disponible. Usá la carga manual.';geoMode.value=geoAvailable.value;localidades.value=[];show.value=true}
async function edit(c:any){editingId.value=c.id;form.value={nombre:c.nombre,apellido:c.apellido,telefono:c.telefono,correo:c.correo??'',localidad:c.localidad,provincia:c.provincia,localidadId:c.localidadId??'',provinciaId:c.provinciaId??'',tipo:c.tipo,fechaPrimerContacto:c.fechaPrimerContacto,observaciones:c.observaciones??''};error.value='';geoMode.value=geoAvailable.value&&!!c.provinciaId&&!!c.localidadId;geoNotice.value=!geoMode.value&&geoAvailable.value?'Esta ubicación proviene de datos históricos. Podés conservarla o normalizarla con Georef.':'';show.value=true;if(geoMode.value)await loadLocalidades()}
async function provinceChanged(){const option=provincias.value.find(x=>x.id===form.value.provinciaId);form.value.provincia=option?.nombre??'';form.value.localidad='';form.value.localidadId='';await loadLocalidades()}
function localitySelected(option:GeoOption){form.value.localidad=option.nombre}
function enableOfficial(){geoMode.value=true;geoNotice.value='';form.value.provincia='';form.value.localidad='';form.value.provinciaId='';form.value.localidadId='';localidades.value=[]}
function useManual(){geoMode.value=false;form.value.provinciaId='';form.value.localidadId='';geoNotice.value='Ubicación en modo manual: se guardarán los nombres sin códigos oficiales.'}
function apiError(e:any){const errors=e.response?.data?.errors;if(errors){const first=Object.values(errors).flat()[0];if(first)return String(first)}return apiErrorMessage(e,'No se pudo guardar el cliente.')}
async function save(){if(geoMode.value&&(!form.value.provinciaId||!form.value.localidadId)){error.value='Seleccioná una provincia y una localidad de las opciones oficiales.';return}try{if(editingId.value)await http.put(`/clientes/${editingId.value}`,form.value);else await http.post('/clientes',form.value);show.value=false;await load()}catch(e:any){error.value=apiError(e)}}
async function remove(c:any){if(!await confirmAction({title:'Eliminar cliente',message:`¿Querés eliminar a ${c.nombreCompleto}?`,confirmText:'Eliminar',danger:true}))return;try{await http.delete(`/clientes/${c.id}`);await load()}catch(e:any){notify(apiErrorMessage(e,'No se pudo eliminar el cliente.'))}}
onMounted(async()=>{await Promise.all([load(),loadProvincias()])})
</script>
<template>
  <section class="page">
    <div class="page-title"><div><h2>Clientes</h2><p>Personas y organizaciones con las que trabajás.</p></div><button class="btn" @click="create">+ Nuevo cliente</button></div>
    <form class="panel client-filters" @submit.prevent="load(true)"><div class="field"><label>Buscar cliente</label><input v-model="buscar" type="search" placeholder="Nombre o apellido"></div><div class="filter-actions"><button class="btn" :disabled="loading">Buscar</button><button type="button" class="btn secondary" @click="buscar='';load(true)">Limpiar</button></div></form>
    <div v-if="loadError" class="error load-state">{{loadError}} <button class="btn secondary compact" @click="load()">Reintentar</button></div>
    <div v-else class="panel"><div class="panel-head"><h3>{{pluralize(total,'cliente','clientes')}}</h3></div><div v-if="loading" class="loading">Cargando clientes…</div><table v-else><thead><tr><th>Nombre</th><th>Tipo</th><th>Contacto</th><th>Ubicación</th><th></th></tr></thead><tbody><tr v-for="c in items" :key="c.id"><td><b>{{c.nombreCompleto}}</b></td><td><span class="badge">{{c.tipo}}</span></td><td>{{c.telefono}}<br><small>{{c.correo}}</small></td><td>{{c.localidad}}, {{c.provincia}}<br><span class="badge" :class="{warn:!c.localidadId}">{{c.localidadId?'Ubicación oficial':'Dato histórico/manual'}}</span></td><td><div class="row-actions"><button class="icon-btn" title="Editar cliente" @click="edit(c)"><Pencil/></button><button class="icon-btn danger" title="Eliminar cliente" @click="remove(c)"><Trash2/></button></div></td></tr></tbody></table><div v-if="!loading&&!items.length" class="empty">No se encontraron clientes.</div><div v-if="totalPages>1" class="actions"><button class="btn secondary" :disabled="page<=1||loading" @click="changePage(page-1)">Anterior</button><span>Página {{page}} de {{totalPages}}</span><button class="btn secondary" :disabled="page>=totalPages||loading" @click="changePage(page+1)">Siguiente</button></div></div>
    <div v-if="show" class="modal-bg"><form class="modal" @submit.prevent="save"><h3>{{editingId?'Editar':'Nuevo'}} cliente</h3><p v-if="error" class="error">{{error}}</p><p v-if="geoNotice" class="load-state">{{geoNotice}}</p><div class="form-grid"><div v-for="field in fields" :key="field.key" class="field"><label>{{field.label}}</label><input v-model="(form as any)[field.key]" :type="field.type" :required="field.key!=='correo'" :maxlength="field.key==='telefono'?30:field.key==='correo'?200:100" :pattern="field.key==='telefono'?'\\+?[0-9 ()-]{6,30}':undefined"></div><template v-if="geoMode"><div class="field full-field"><span class="badge">Ubicación oficial de Argentina</span></div><div class="field"><label>País</label><input value="Argentina" readonly></div><div class="field"><label>Provincia</label><select v-model="form.provinciaId" required @change="provinceChanged"><option value="">Seleccionar provincia</option><option v-for="p in provincias" :key="p.id" :value="p.id">{{p.nombre}}</option></select></div><div class="field"><label>Localidad</label><GeografiaAutocomplete v-model="form.localidadId" :options="localidades" :disabled="!form.provinciaId||geoLoading" :placeholder="geoLoading?'Cargando localidades…':'Buscar localidad'" @select="localitySelected"/></div><div class="field"><label>Origen</label><button type="button" class="btn secondary" @click="useManual">Cargar manualmente (sin normalizar)</button></div></template><template v-else><div class="field full-field"><span class="badge warn">Modo manual: la ubicación se guardará sin códigos oficiales.</span></div><div class="field"><label>Provincia</label><input v-model="form.provincia" maxlength="100" required></div><div class="field"><label>Localidad</label><input v-model="form.localidad" maxlength="100" required></div><div v-if="geoAvailable" class="field full-field"><button type="button" class="btn secondary" @click="enableOfficial">Usar ubicaciones oficiales de Argentina</button></div></template><div class="field"><label>Tipo</label><select v-model="form.tipo"><option v-for="t in ['Particular','Club','Empresa','Constructor','Revendedor','Otro']" :key="t">{{t}}</option></select></div><div class="field"><label>Primer contacto</label><input v-model="form.fechaPrimerContacto" type="date" required></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" maxlength="1000" rows="3"></textarea></div></div><div class="actions"><button type="button" class="btn secondary" @click="show=false">Cancelar</button><button class="btn">{{editingId?'Guardar cambios':'Guardar cliente'}}</button></div></form></div>
  </section>
</template>
