<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Pencil, Trash2 } from 'lucide-vue-next'
import { http } from '@/shared/api/httpClient'
import { confirmAction, notify } from '@/shared/uiFeedback'

const items=ref<any[]>([]),show=ref(false),error=ref(''),editingId=ref<string|null>(null)
const fields=[{key:'nombre',label:'Nombre',type:'text'},{key:'apellido',label:'Apellido',type:'text'},{key:'telefono',label:'Teléfono',type:'tel'},{key:'correo',label:'Correo electrónico',type:'email'},{key:'localidad',label:'Localidad',type:'text'},{key:'provincia',label:'Provincia',type:'text'}] as const
const blank=()=>({nombre:'',apellido:'',telefono:'',correo:'',localidad:'',provincia:'',tipo:'Particular',fechaPrimerContacto:new Date().toISOString().slice(0,10),observaciones:''})
const form=ref(blank())
async function load(){items.value=(await http.get('/clientes?pageSize=100')).data.items}
function create(){editingId.value=null;form.value=blank();error.value='';show.value=true}
function edit(c:any){editingId.value=c.id;form.value={nombre:c.nombre,apellido:c.apellido,telefono:c.telefono,correo:c.correo??'',localidad:c.localidad,provincia:c.provincia,tipo:c.tipo,fechaPrimerContacto:c.fechaPrimerContacto,observaciones:c.observaciones??''};error.value='';show.value=true}
function apiError(e:any){const errors=e.response?.data?.errors;if(errors){const first=Object.values(errors).flat()[0];if(first)return String(first)}return e.response?.data?.detail??e.response?.data?.message??'No se pudo guardar el cliente.'}
async function save(){try{if(editingId.value)await http.put(`/clientes/${editingId.value}`,form.value);else await http.post('/clientes',form.value);show.value=false;await load()}catch(e:any){error.value=apiError(e)}}
async function remove(c:any){if(!await confirmAction({title:'Eliminar cliente',message:`¿Querés eliminar a ${c.nombreCompleto}?`,confirmText:'Eliminar',danger:true}))return;try{await http.delete(`/clientes/${c.id}`);await load()}catch(e:any){notify(e.response?.data?.message??'No se pudo eliminar el cliente.')}}
onMounted(load)
</script>
<template><section class="page"><div class="page-title"><div><h2>Clientes</h2><p>Personas y organizaciones con las que trabajás.</p></div><button class="btn" @click="create">+ Nuevo cliente</button></div><div class="panel"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Contacto</th><th>Ubicación</th><th></th></tr></thead><tbody><tr v-for="c in items" :key="c.id"><td><b>{{c.nombreCompleto}}</b></td><td><span class="badge">{{c.tipo}}</span></td><td>{{c.telefono}}<br><small>{{c.correo}}</small></td><td>{{c.localidad}}, {{c.provincia}}</td><td><div class="row-actions"><button class="icon-btn" title="Editar cliente" @click="edit(c)"><Pencil/></button><button class="icon-btn danger" title="Eliminar cliente" @click="remove(c)"><Trash2/></button></div></td></tr></tbody></table><div v-if="!items.length" class="empty">Agregá tu primer cliente para comenzar.</div></div><div v-if="show" class="modal-bg"><form class="modal" @submit.prevent="save"><h3>{{editingId?'Editar':'Nuevo'}} cliente</h3><p v-if="error" class="error">{{error}}</p><div class="form-grid"><div v-for="field in fields" :key="field.key" class="field"><label>{{field.label}}</label><input v-model="(form as any)[field.key]" :type="field.type" :required="field.key!=='correo'" :maxlength="field.key==='telefono'?30:field.key==='correo'?200:100" :pattern="field.key==='telefono'?'\\+?[0-9 ()-]{6,30}':undefined"></div><div class="field"><label>Tipo</label><select v-model="form.tipo"><option v-for="t in ['Particular','Club','Empresa','Constructor','Revendedor','Otro']" :key="t">{{t}}</option></select></div><div class="field"><label>Primer contacto</label><input v-model="form.fechaPrimerContacto" type="date" required></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" maxlength="1000" rows="3"></textarea></div></div><div class="actions"><button type="button" class="btn secondary" @click="show=false">Cancelar</button><button class="btn">{{editingId?'Guardar cambios':'Guardar cliente'}}</button></div></form></div></section></template>
