<script setup lang="ts">
import{ref,onMounted}from'vue'
import{http}from'@/shared/api/httpClient'
import{formatCurrency as money}from'@/shared/formatters'
import{auth}from'@/auth'
const ventas=ref<any[]>([]),caja=ref(0),cuotasPendientes=ref(0),hoy=ref({cantidad:0,facturacion:0,metros:0}),mes=ref({cantidad:0,facturacion:0,metros:0}),loading=ref(false),loadError=ref('')
async function load(){loading.value=true;loadError.value='';try{const{data}=await http.get('/dashboard');ventas.value=data.ventas;caja.value=data.saldo;cuotasPendientes.value=data.cuotasPendientes;hoy.value=data.hoy;mes.value=data.mes}catch{loadError.value='No se pudo cargar el resumen del sistema.'}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="page"><div class="page-title"><div><h2>Hola, {{auth.state.user?.nombre||'bienvenido'}}</h2><p>Una vista rápida de tu operación comercial.</p></div><RouterLink v-if="auth.can('ventas')" class="btn" to="/ventas">+ Nueva venta</RouterLink></div><div v-if="loadError" class="error load-state">{{loadError}} <button class="btn secondary compact" @click="load">Reintentar</button></div><div v-else-if="loading" class="panel loading">Cargando resumen…</div><template v-else><div class="grid"><article class="card metric"><small>Facturación del mes</small><strong>{{money(mes.facturacion)}}</strong><em>{{mes.cantidad}} operaciones · hoy {{money(hoy.facturacion)}}</em></article><article class="card metric"><small>Saldo en caja</small><strong>{{money(caja)}}</strong><em>Saldo calculado en tiempo real</em></article><article class="card metric"><small>Cuotas pendientes</small><strong>{{cuotasPendientes}}</strong><em>Requieren seguimiento</em></article><article class="card metric"><small>Metros vendidos este mes</small><strong>{{mes.metros}} m²</strong><em>Hoy: {{hoy.metros}} m² en {{hoy.cantidad}} operaciones</em></article></div><div class="panel"><div class="panel-head"><h3>Últimas ventas</h3><RouterLink v-if="auth.can('ventas')" to="/ventas">Ver todas</RouterLink></div><table><thead><tr><th>Cliente</th><th>Producto</th><th>Fecha</th><th>Total</th><th>Estado</th></tr></thead><tbody><tr v-for="v in ventas" :key="v.id"><td><b>{{v.cliente}}</b></td><td>{{v.tipoCesped}}</td><td>{{v.fechaVenta}}</td><td>{{money(v.precioTotal)}}</td><td><span class="badge">{{v.estado}}</span></td></tr></tbody></table><div v-if="!ventas.length" class="empty">Todavía no hay ventas registradas.</div></div></template></section></template>
