<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Pencil, Trash2 } from 'lucide-vue-next'
import { http, apiErrorMessage } from '@/shared/api/httpClient'
import { formatCurrency as money, pluralize } from '@/shared/formatters'
import { confirmAction, notify } from '@/shared/uiFeedback'

const today=new Date(),monthStart=new Date(today.getFullYear(),today.getMonth(),1)
const iso=(date:Date)=>date.toISOString().slice(0,10)
const items=ref<any[]>([]),total=ref(0),totalImporte=ref(0),page=ref(1),totalPages=ref(1),loading=ref(false),loadError=ref('')
const filters=ref({desde:iso(monthStart),hasta:iso(today),buscar:''})
const show=ref(false),editingId=ref<string|null>(null),saving=ref(false),error=ref('')
const blank=()=>({fecha:iso(new Date()),categoria:'',descripcion:'',importe:0,observaciones:''})
const form=ref(blank())

async function load(reset=false){if(reset)page.value=1;loading.value=true;loadError.value='';try{const{data}=await http.get('/gastos',{params:{...filters.value,buscar:filters.value.buscar.trim()||undefined,page:page.value,pageSize:50}});items.value=data.items;total.value=data.total;totalImporte.value=data.totalImporte;totalPages.value=data.totalPages}catch(e:any){loadError.value=apiErrorMessage(e,'No se pudieron cargar los gastos.')}finally{loading.value=false}}
function create(){editingId.value=null;form.value=blank();error.value='';show.value=true}
function edit(x:any){editingId.value=x.id;form.value={fecha:x.fecha,categoria:x.categoria,descripcion:x.descripcion,importe:x.importe,observaciones:x.observaciones??''};error.value='';show.value=true}
async function save(){saving.value=true;error.value='';try{editingId.value?await http.put(`/gastos/${editingId.value}`,form.value):await http.post('/gastos',form.value);show.value=false;await load()}catch(e:any){error.value=apiErrorMessage(e,'No se pudo guardar el gasto.')}finally{saving.value=false}}
async function remove(x:any){if(!await confirmAction({title:'Eliminar gasto',message:`¿Querés eliminar “${x.descripcion}” por ${money(x.importe)}?`,confirmText:'Eliminar',danger:true}))return;try{await http.delete(`/gastos/${x.id}`);await load()}catch(e:any){notify(apiErrorMessage(e,'No se pudo eliminar el gasto.'))}}
function resetFilters(){filters.value={desde:iso(monthStart),hasta:iso(today),buscar:''};load(true)}
function changePage(value:number){page.value=value;load()}
onMounted(()=>load())
</script>

<template><section class="page"><div class="page-title"><div><h2>Gastos</h2><p>Registro independiente de gastos generales.</p></div><button class="btn" @click="create">+ Nuevo gasto</button></div>
<form class="panel rentabilidad-filters" @submit.prevent="load(true)"><div class="field"><label>Desde</label><input v-model="filters.desde" type="date"></div><div class="field"><label>Hasta</label><input v-model="filters.hasta" type="date"></div><div class="field"><label>Buscar</label><input v-model="filters.buscar" type="search" placeholder="Categoría, descripción u observación"></div><div class="filter-actions"><button class="btn" :disabled="loading">Aplicar filtros</button><button type="button" class="btn secondary" @click="resetFilters">Restablecer</button></div></form>
<div v-if="loadError" class="error load-state">{{loadError}} <button class="btn secondary compact" @click="load()">Reintentar</button></div><template v-else><div class="grid"><article class="card metric"><small>Total del período</small><strong>{{money(totalImporte)}}</strong><em>{{pluralize(total,'gasto registrado','gastos registrados')}}</em></article></div><div class="panel"><div class="panel-head"><h3>{{pluralize(total,'gasto','gastos')}}</h3></div><div v-if="loading" class="loading">Cargando gastos…</div><table v-else><thead><tr><th>Fecha</th><th>Categoría</th><th>Descripción</th><th>Observaciones</th><th class="num">Importe</th><th></th></tr></thead><tbody><tr v-for="x in items" :key="x.id"><td>{{new Date(`${x.fecha}T00:00:00`).toLocaleDateString('es-AR')}}</td><td><span class="badge">{{x.categoria}}</span></td><td><b>{{x.descripcion}}</b></td><td>{{x.observaciones||'—'}}</td><td class="num"><b>{{money(x.importe)}}</b></td><td><div class="row-actions"><button class="icon-btn" title="Editar gasto" @click="edit(x)"><Pencil/></button><button class="icon-btn danger" title="Eliminar gasto" @click="remove(x)"><Trash2/></button></div></td></tr></tbody></table><div v-if="!loading&&!items.length" class="empty">No hay gastos para los filtros seleccionados.</div><div v-if="totalPages>1" class="actions"><button class="btn secondary" :disabled="page<=1" @click="changePage(page-1)">Anterior</button><span>Página {{page}} de {{totalPages}}</span><button class="btn secondary" :disabled="page>=totalPages" @click="changePage(page+1)">Siguiente</button></div></div></template>
<div v-if="show" class="modal-bg"><form class="modal" @submit.prevent="save"><h3>{{editingId?'Editar':'Nuevo'}} gasto</h3><p>Este registro no modifica Caja, Rentabilidad ni otras vistas.</p><p v-if="error" class="error">{{error}}</p><div class="form-grid"><div class="field"><label>Fecha</label><input v-model="form.fecha" type="date" required></div><div class="field"><label>Categoría</label><input v-model="form.categoria" maxlength="100" placeholder="Ej.: Servicios, insumos, alquiler" required></div><div class="field full-field"><label>Descripción</label><input v-model="form.descripcion" maxlength="300" required></div><div class="field"><label>Importe</label><input v-model.number="form.importe" type="number" min="0.01" step="0.01" required></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" maxlength="1000" rows="3"></textarea></div></div><div class="actions"><button type="button" class="btn secondary" @click="show=false">Cancelar</button><button class="btn" :disabled="saving">{{saving?'Guardando…':'Guardar gasto'}}</button></div></form></div></section></template>
