<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Plus, Trash2 } from "lucide-vue-next";
import { useRoute, useRouter } from "vue-router";
import { http } from "@/shared/api/httpClient";
import { formatCurrency as money } from "@/shared/formatters";
import ClienteAutocomplete from "@/shared/components/ClienteAutocomplete.vue";

const router = useRouter();
const route = useRoute();
const editingId = computed(() => typeof route.params.id === "string" ? route.params.id : "");
const clientes = ref<any[]>([]), maestros = ref<any>({ tiposCesped: [], alicuotasIva: [] });
const saving = ref(false), error = ref("");
const line = () => ({ tipoCespedId: "", color: "", cantidadM2: 1, precioCompraM2: 0, precioVentaM2: 0, total: 0 });
const form = ref({ clienteId: "", fechaVenta: new Date().toISOString().slice(0, 10), lineas: [line()],
  montoEntrega: 0, formaPago: "Contado", cantidadCuotas: null as number|null, estado: "Confirmada",
  fechaEntregaEstimada: null as string|null, costoEnvio: 0, otrosCostos: 0, alicuotaIvaId: "", observaciones: "" });
const totalProductos = computed(() => form.value.lineas.reduce((sum, x) => sum + Number(x.total || 0), 0));
const totalVenta = computed(() => totalProductos.value);
function product(row:any){return maestros.value.tiposCesped.find((x:any)=>x.id===row.tipoCespedId)}
function selectProduct(row:any){const p=product(row);if(!p)return;row.precioCompraM2=p.costoM2;row.precioVentaM2=p.precioVentaM2;row.color=p.colores?.length===1?p.colores[0]:"";recalculate(row)}
function recalculate(row:any){row.total=Math.round(Number(row.cantidadM2||0)*Number(row.precioVentaM2||0)*100)/100}
function addLine(){form.value.lineas.push(line())}
function removeLine(index:number){if(form.value.lineas.length>1)form.value.lineas.splice(index,1)}
async function load(){const [filters, masters]=await Promise.all([http.get("/ventas/filtros"),http.get("/maestros")]);clientes.value=filters.data.clientes;maestros.value=masters.data;form.value.alicuotaIvaId=masters.data.alicuotasIva?.[0]?.id??"";if(editingId.value){const v=(await http.get(`/ventas/${editingId.value}`)).data;form.value={clienteId:v.clienteId,fechaVenta:v.fechaVenta,lineas:v.lineas?.length?v.lineas:[{tipoCespedId:v.tipoCespedId,color:v.color??"",cantidadM2:v.cantidadM2,precioCompraM2:v.costoCompraUnitario,precioVentaM2:v.precioUnitario,total:v.precioTotal}],montoEntrega:v.montoEntrega,formaPago:v.formaPago,cantidadCuotas:v.cantidadCuotas,estado:v.estado,fechaEntregaEstimada:v.fechaEntregaEstimada,costoEnvio:v.costoEnvio,otrosCostos:v.otrosCostos,alicuotaIvaId:v.alicuotaIvaId,observaciones:v.observaciones??""}}}
async function save(){error.value="";saving.value=true;try{const first=form.value.lineas[0]!;const payload={...form.value,
  tipoCespedId:first.tipoCespedId,color:first.color,cantidadM2:form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0),
  precioUnitario:totalProductos.value/form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0),precioTotal:totalProductos.value,
  costoCompraUnitario:form.value.lineas.reduce((s,x)=>s+Number(x.precioCompraM2)*Number(x.cantidadM2),0)/form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0)};editingId.value?await http.put(`/ventas/${editingId.value}`,payload):await http.post("/ventas",payload);await router.push("/ventas")}
  catch(e:any){error.value=e.response?.data?.detail??Object.values(e.response?.data?.errors??{}).flat()[0]??"Revisá los datos ingresados."}finally{saving.value=false}}
onMounted(load);
</script>

<template><section class="page sale-create-page"><div class="page-title"><div><h2>{{editingId?'Modificar venta':'Nueva venta'}}</h2><p>Seleccioná el cliente, agregá los productos y acordá el pago.</p></div><RouterLink class="btn secondary" to="/ventas">Volver a ventas</RouterLink></div>
<form @submit.prevent="save"><p v-if="error" class="error">{{error}}</p>
<section class="panel sale-step"><div class="panel-head"><h3>1. Cliente</h3></div><div class="sale-step-body"><div class="field"><label>Cliente</label><ClienteAutocomplete v-model="form.clienteId" :clientes="clientes" /></div><div class="field"><label>Fecha de venta</label><input v-model="form.fechaVenta" type="date" required></div></div></section>
<section class="panel sale-step"><div class="panel-head"><h3>2. Productos</h3><button type="button" class="btn secondary compact" @click="addLine"><Plus/> Agregar producto</button></div><div class="sale-lines"><article v-for="(row,index) in form.lineas" :key="index" class="sale-line"><div class="field"><label>Producto</label><select v-model="row.tipoCespedId" required @change="selectProduct(row)"><option value="" disabled>Seleccionar</option><option v-for="p in maestros.tiposCesped" :key="p.id" :value="p.id">{{p.nombre}}</option></select></div><div v-if="product(row)?.colores?.length" class="field"><label>Color</label><select v-model="row.color" required><option value="" disabled>Seleccionar</option><option v-for="color in product(row).colores" :key="color">{{color}}</option></select></div><div class="field"><label>Metros m²</label><input v-model.number="row.cantidadM2" type="number" min="0.01" step="0.01" required @input="recalculate(row)"></div><div class="field"><label>Costo compra / m²</label><input v-model.number="row.precioCompraM2" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Precio venta / m²</label><input v-model.number="row.precioVentaM2" type="number" min="0.01" step="0.01" required @input="recalculate(row)"></div><div class="field highlight-field"><label>Total de la línea</label><input v-model.number="row.total" type="number" min="0.01" step="0.01" required><small>Cálculo: {{money(Number(row.cantidadM2)*Number(row.precioVentaM2))}}</small></div><button type="button" class="icon-btn danger sale-line-remove" :disabled="form.lineas.length===1" title="Quitar producto" @click="removeLine(index)"><Trash2/></button></article></div><div class="sale-products-total"><span>Total productos</span><strong>{{money(totalProductos)}}</strong></div></section>
<section class="panel sale-step"><div class="panel-head"><h3>3. Entrega y pago</h3></div><div class="form-grid sale-step-body"><div class="field"><label>Estado</label><select v-model="form.estado"><option v-for="x in ['Confirmada','Futura','Entregada','Cancelada']" :key="x">{{x}}</option></select></div><div v-if="form.estado==='Futura'" class="field"><label>Entrega estimada</label><input v-model="form.fechaEntregaEstimada" type="date" required></div><div class="field"><label>Envío</label><input v-model.number="form.costoEnvio" type="number" min="0" step="0.01"></div><div class="field"><label>Otros costos</label><input v-model.number="form.otrosCostos" type="number" min="0" step="0.01"></div><div class="field"><label>IVA</label><select v-model="form.alicuotaIvaId" required><option v-for="a in maestros.alicuotasIva" :key="a.id" :value="a.id">{{a.nombre}}</option></select></div><div class="field"><label>Forma de pago</label><select v-model="form.formaPago"><option v-for="x in ['Contado','Transferencia','Cheque','Cuotas','Otros']" :key="x">{{x}}</option></select></div><div v-if="form.formaPago==='Cuotas'" class="field"><label>Cuotas sobre el saldo</label><input v-model.number="form.cantidadCuotas" type="number" min="1" max="60" required></div><div class="field highlight-field"><label>Entrega inicial</label><input v-model.number="form.montoEntrega" type="number" min="0.01" :max="totalProductos" step="0.01" required><small>Se registra como ingreso en Caja.</small></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" rows="3"></textarea></div></div><div class="sale-final-total"><span>Total final de la venta</span><strong>{{money(totalVenta)}}</strong><small>Los costos de envío y otros costos afectan rentabilidad, no el importe cobrado por productos.</small></div></section>
<div class="actions"><RouterLink class="btn secondary" to="/ventas">Cancelar</RouterLink><button class="btn" :disabled="saving">{{saving?'Guardando…':editingId?'Guardar cambios':'Confirmar venta'}}</button></div></form></section></template>
