<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Check, Pencil, Plus, Trash2 } from "lucide-vue-next";
import { useRoute, useRouter } from "vue-router";
import { http } from "@/shared/api/httpClient";
import { formatCurrency as money } from "@/shared/formatters";
import ClienteAutocomplete from "@/shared/components/ClienteAutocomplete.vue";

const router = useRouter();
const route = useRoute();
const editingId = computed(() => typeof route.params.id === "string" ? route.params.id : "");
const clientes = ref<any[]>([]), maestros = ref<any>({ tiposCesped: [], alicuotasIva: [] });
const saving = ref(false), error = ref(""), editingLine = ref<number|null>(null);
const line = () => ({ tipoCespedId: "", color: "", cantidadM2: 1, precioCompraM2: 0, precioVentaM2: 0, total: 0 });
const draft = ref(line());
const form = ref({ clienteId: "", fechaVenta: new Date().toISOString().slice(0, 10), lineas: [] as ReturnType<typeof line>[],
  montoEntrega: 0, formaPago: "Contado", cantidadCuotas: null as number|null, estado: "Confirmada",
  fechaEntregaEstimada: null as string|null, costoEnvio: 0, otrosCostos: 0, alicuotaIvaId: "", observaciones: "" });
const totalProductos = computed(() => form.value.lineas.reduce((sum, x) => sum + Number(x.total || 0), 0));
const totalVenta = computed(() => totalProductos.value);
function product(row:any){return maestros.value.tiposCesped.find((x:any)=>x.id===row.tipoCespedId)}
function selectProduct(row:any){const p=product(row);if(!p)return;row.precioCompraM2=p.costoM2;row.precioVentaM2=p.precioVentaM2;row.color=p.colores?.length===1?p.colores[0]:"";recalculate(row)}
function recalculate(row:any){row.total=Math.round(Number(row.cantidadM2||0)*Number(row.precioVentaM2||0)*100)/100}
function saveLine(){if(!draft.value.tipoCespedId||draft.value.cantidadM2<=0||draft.value.precioCompraM2<=0||draft.value.precioVentaM2<=0||draft.value.total<=0){error.value="Completá todos los datos del producto antes de agregarlo.";return}if(editingLine.value===null)form.value.lineas.push({...draft.value});else form.value.lineas[editingLine.value]={...draft.value};draft.value=line();editingLine.value=null;error.value=""}
function editLine(index:number){draft.value={...form.value.lineas[index]!};editingLine.value=index;window.scrollTo({top:300,behavior:"smooth"})}
function removeLine(index:number){form.value.lineas.splice(index,1);if(editingLine.value===index){draft.value=line();editingLine.value=null}}
function productName(id:string){return maestros.value.tiposCesped.find((x:any)=>x.id===id)?.nombre??"Producto"}
async function load(){const [filters, masters]=await Promise.all([http.get("/ventas/filtros"),http.get("/maestros")]);clientes.value=filters.data.clientes;maestros.value=masters.data;form.value.alicuotaIvaId=masters.data.alicuotasIva?.[0]?.id??"";if(editingId.value){const v=(await http.get(`/ventas/${editingId.value}`)).data;form.value={clienteId:v.clienteId,fechaVenta:v.fechaVenta,lineas:v.lineas?.length?v.lineas:[{tipoCespedId:v.tipoCespedId,color:v.color??"",cantidadM2:v.cantidadM2,precioCompraM2:v.costoCompraUnitario,precioVentaM2:v.precioUnitario,total:v.precioTotal}],montoEntrega:v.montoEntrega,formaPago:v.formaPago,cantidadCuotas:v.cantidadCuotas,estado:v.estado,fechaEntregaEstimada:v.fechaEntregaEstimada,costoEnvio:v.costoEnvio,otrosCostos:v.otrosCostos,alicuotaIvaId:v.alicuotaIvaId,observaciones:v.observaciones??""}}}
async function save(){error.value="";if(!form.value.lineas.length){error.value="Agregá al menos un producto a la venta.";return}saving.value=true;try{const first=form.value.lineas[0]!;const payload={...form.value,
  tipoCespedId:first.tipoCespedId,color:first.color,cantidadM2:form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0),
  precioUnitario:totalProductos.value/form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0),precioTotal:totalProductos.value,
  costoCompraUnitario:form.value.lineas.reduce((s,x)=>s+Number(x.precioCompraM2)*Number(x.cantidadM2),0)/form.value.lineas.reduce((s,x)=>s+Number(x.cantidadM2),0)};editingId.value?await http.put(`/ventas/${editingId.value}`,payload):await http.post("/ventas",payload);await router.push("/ventas")}
  catch(e:any){error.value=e.response?.data?.detail??Object.values(e.response?.data?.errors??{}).flat()[0]??"Revisá los datos ingresados."}finally{saving.value=false}}
onMounted(load);
</script>

<template><section class="page sale-create-page"><div class="page-title"><div><h2>{{editingId?'Modificar venta':'Nueva venta'}}</h2><p>Seleccioná el cliente, agregá los productos y acordá el pago.</p></div><RouterLink class="btn secondary" to="/ventas">Volver a ventas</RouterLink></div>
<form @submit.prevent="save"><p v-if="error" class="error">{{error}}</p>
<section class="panel sale-step"><div class="panel-head"><h3>1. Cliente</h3></div><div class="sale-step-body"><div class="field"><label>Cliente</label><ClienteAutocomplete v-model="form.clienteId" :clientes="clientes" /></div><div class="field"><label>Fecha de venta</label><input v-model="form.fechaVenta" type="date" required></div></div></section>
<section class="panel sale-step sale-detail-panel"><div class="panel-head"><div><h3>2. Detalle de productos</h3><small>Cargá una línea y agregala al comprobante.</small></div></div>
<div class="sale-entry"><div class="field sale-product-field"><label>Producto</label><select v-model="draft.tipoCespedId" @change="selectProduct(draft)"><option value="" disabled>Seleccionar producto</option><option v-for="p in maestros.tiposCesped" :key="p.id" :value="p.id">{{p.nombre}}</option></select></div><div v-if="product(draft)?.colores?.length" class="field"><label>Color</label><select v-model="draft.color"><option value="" disabled>Seleccionar</option><option v-for="color in product(draft).colores" :key="color">{{color}}</option></select></div><div class="field"><label>Metros m²</label><input v-model.number="draft.cantidadM2" type="number" min="0.01" step="0.01" @input="recalculate(draft)"></div><div class="field"><label>Costo / m²</label><input v-model.number="draft.precioCompraM2" type="number" min="0.01" step="0.01"></div><div class="field"><label>Venta / m²</label><input v-model.number="draft.precioVentaM2" type="number" min="0.01" step="0.01" @input="recalculate(draft)"></div><div class="field highlight-field"><label>Total</label><input v-model.number="draft.total" type="number" min="0.01" step="0.01"><small>Editable · cálculo {{money(Number(draft.cantidadM2)*Number(draft.precioVentaM2))}}</small></div><button type="button" class="btn sale-add-button" @click="saveLine"><Check v-if="editingLine!==null"/><Plus v-else/>{{editingLine!==null?'Actualizar':'Agregar'}}</button></div>
<div class="sale-table-wrap"><table class="sale-detail-table"><thead><tr><th>#</th><th>Producto</th><th>Color</th><th class="num">Metros</th><th class="num">Costo / m²</th><th class="num">Venta / m²</th><th class="num">Total</th><th></th></tr></thead><tbody><tr v-for="(row,index) in form.lineas" :key="index"><td>{{index+1}}</td><td><b>{{productName(row.tipoCespedId)}}</b></td><td>{{row.color||'—'}}</td><td class="num">{{row.cantidadM2}} m²</td><td class="num">{{money(row.precioCompraM2)}}</td><td class="num">{{money(row.precioVentaM2)}}</td><td class="num"><b>{{money(row.total)}}</b></td><td><div class="row-actions"><button type="button" class="icon-btn" title="Editar línea" @click="editLine(index)"><Pencil/></button><button type="button" class="icon-btn danger" title="Quitar línea" @click="removeLine(index)"><Trash2/></button></div></td></tr></tbody></table><div v-if="!form.lineas.length" class="empty">Todavía no agregaste productos a la venta.</div></div><div class="sale-products-total"><span>Subtotal de productos</span><strong>{{money(totalProductos)}}</strong></div></section>
<section class="panel sale-step"><div class="panel-head"><h3>3. Entrega y pago</h3></div><div class="form-grid sale-step-body"><div class="field"><label>Estado</label><select v-model="form.estado"><option v-for="x in ['Confirmada','Futura','Entregada','Cancelada']" :key="x">{{x}}</option></select></div><div v-if="form.estado==='Futura'" class="field"><label>Entrega estimada</label><input v-model="form.fechaEntregaEstimada" type="date" required></div><div class="field"><label>Envío</label><input v-model.number="form.costoEnvio" type="number" min="0" step="0.01"></div><div class="field"><label>Otros costos</label><input v-model.number="form.otrosCostos" type="number" min="0" step="0.01"></div><div class="field"><label>IVA</label><select v-model="form.alicuotaIvaId" required><option v-for="a in maestros.alicuotasIva" :key="a.id" :value="a.id">{{a.nombre}}</option></select></div><div class="field"><label>Forma de pago</label><select v-model="form.formaPago"><option v-for="x in ['Contado','Transferencia','Cheque','Cuotas','Otros']" :key="x">{{x}}</option></select></div><div v-if="form.formaPago==='Cuotas'" class="field"><label>Cuotas sobre el saldo</label><input v-model.number="form.cantidadCuotas" type="number" min="1" max="60" required></div><div class="field highlight-field"><label>Entrega inicial</label><input v-model.number="form.montoEntrega" type="number" min="0.01" :max="totalProductos" step="0.01" required><small>Se registra como ingreso en Caja.</small></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" rows="3"></textarea></div></div><div class="sale-final-total"><span>Total final de la venta</span><strong>{{money(totalVenta)}}</strong><small>Los costos de envío y otros costos afectan rentabilidad, no el importe cobrado por productos.</small></div></section>
<div class="actions"><RouterLink class="btn secondary" to="/ventas">Cancelar</RouterLink><button class="btn" :disabled="saving">{{saving?'Guardando…':editingId?'Guardar cambios':'Confirmar venta'}}</button></div></form></section></template>
