<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Plus, Trash2 } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { http, apiErrorMessage } from '@/shared/api/httpClient'
import ClienteAutocomplete from '@/shared/components/ClienteAutocomplete.vue'
import NuevoClienteModal from '@/shared/components/NuevoClienteModal.vue'
import { auth } from '@/auth'
const route=useRoute(),router=useRouter(),id=computed(()=>String(route.params.id??'')),clientes=ref<any[]>([]),productos=ref<any[]>([]),saving=ref(false),error=ref(''),showNewClient=ref(false)
const today=new Date()
function addDay(value:string){const date=new Date(`${value}T00:00:00`);date.setDate(date.getDate()+1);return date.toISOString().slice(0,10)}
const blankLine=()=>({tipoCespedId:'',color:'',cantidadM2:1,precioContadoM2:0,precioFinanciadoM2:0})
const initialDate=today.toISOString().slice(0,10)
const form=ref({clienteId:'',fecha:initialDate,validezHasta:addDay(initialDate),descuentoContadoPorcentaje:0,ivaContadoPorcentaje:10.5,ivaFinanciadoPorcentaje:21,entregaFinanciada:0,observaciones:'',lineas:[blankLine()]})
watch(()=>form.value.fecha,(fecha)=>{form.value.validezHasta=addDay(fecha)})
const subtotalContado=computed(()=>form.value.lineas.reduce((s,l)=>s+Number(l.cantidadM2||0)*Number(l.precioContadoM2||0),0))
const subtotalFinanciado=computed(()=>form.value.lineas.reduce((s,l)=>s+Number(l.cantidadM2||0)*Number(l.precioFinanciadoM2||0),0))
const contado=computed(()=>subtotalContado.value*(1-Number(form.value.descuentoContadoPorcentaje)/100)*(1+Number(form.value.ivaContadoPorcentaje)/100))
const financiado=computed(()=>subtotalFinanciado.value*(1+Number(form.value.ivaFinanciadoPorcentaje)/100))
const entregaConIva=computed(()=>Number(form.value.entregaFinanciada)*1.21)
const saldoFinanciado=computed(()=>financiado.value-entregaConIva.value)
const usd=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'USD'}).format(v)
function product(l:any){return productos.value.find(x=>x.id===l.tipoCespedId)}
function selectProduct(l:any){const p=product(l);if(p){l.precioContadoM2=p.precioContadoM2;l.precioFinanciadoM2=p.precioFinanciadoM2;l.color=''}}
function colors(l:any){const raw=product(l)?.coloresJson;try{return JSON.parse(raw||'[]')}catch{return []}}
function addLine(){form.value.lineas.push(blankLine())}
function removeLine(i:number){if(form.value.lineas.length>1)form.value.lineas.splice(i,1)}
function clientCreated(cliente:any){clientes.value.push(cliente);form.value.clienteId=cliente.id;showNewClient.value=false}
async function load(){const f=(await http.get('/presupuestos/filtros')).data;clientes.value=f.clientes;productos.value=f.productos;if(id.value){const p=(await http.get(`/presupuestos/${id.value}`)).data;form.value={clienteId:p.clienteId,fecha:p.fecha,validezHasta:addDay(p.fecha),descuentoContadoPorcentaje:p.descuentoContadoPorcentaje,ivaContadoPorcentaje:p.ivaContadoPorcentaje,ivaFinanciadoPorcentaje:p.ivaFinanciadoPorcentaje,entregaFinanciada:p.entregaFinanciada,observaciones:p.observaciones??'',lineas:p.lineas.map((l:any)=>({tipoCespedId:l.tipoCespedId,color:l.color??'',cantidadM2:l.cantidadM2,precioContadoM2:l.precioContadoM2,precioFinanciadoM2:l.precioFinanciadoM2}))}}}
async function save(){error.value='';saving.value=true;try{if(!form.value.lineas.every(l=>l.tipoCespedId&&l.cantidadM2>0&&l.precioContadoM2>0&&l.precioFinanciadoM2>0))throw new Error('lines');if(entregaConIva.value>financiado.value)throw new Error('deposit');id.value?await http.put(`/presupuestos/${id.value}`,form.value):await http.post('/presupuestos',form.value);await router.push('/presupuestos')}catch(e:any){const details=Object.values(e.response?.data?.errors??{}).flat().map(String);error.value=e.message==='lines'?'Completá producto, metros y ambos precios en todas las líneas.':e.message==='deposit'?'La entrega más IVA 21% no puede superar el total financiado.':details[0]??apiErrorMessage(e,'Revisá los datos ingresados.')}finally{saving.value=false}}
onMounted(load)
</script>
<template><section class="page quote-create-page"><div class="page-title"><div><h2>{{id?'Editar presupuesto':'Nuevo presupuesto'}}</h2><p>Completá pocos datos y generá una propuesta profesional en USD.</p></div><RouterLink class="btn secondary" to="/presupuestos">Volver</RouterLink></div><form @submit.prevent="save"><p v-if="error" class="error">{{error}}</p>
<section class="panel sale-step"><div class="panel-head"><h3>1. Cliente y vigencia</h3></div><div class="sale-step-body quote-header"><div class="field"><label>Cliente</label><div class="sale-client-picker"><ClienteAutocomplete v-model="form.clienteId" :clientes="clientes"/><button v-if="auth.can('clientes','crear')" type="button" class="btn sale-new-client" title="Agregar nuevo cliente" aria-label="Agregar nuevo cliente" @click="showNewClient=true"><Plus/></button></div></div><div class="field"><label>Fecha</label><input v-model="form.fecha" type="date" required></div><div class="field"><label>Validez</label><div class="quote-validity-note">24 horas desde la emisión</div></div></div></section>
<section class="panel sale-step"><div class="panel-head"><div><h3>2. Productos</h3><small>Los precios contado y financiado se cargan desde Productos y siguen siendo editables.</small></div><button type="button" class="btn secondary compact" @click="addLine"><Plus/> Agregar producto</button></div><div class="quote-lines"><div v-for="(l,i) in form.lineas" :key="i" class="quote-line"><div class="field"><label>Producto</label><select v-model="l.tipoCespedId" required @change="selectProduct(l)"><option value="" disabled>Seleccionar producto</option><option v-for="p in productos" :key="p.id" :value="p.id">{{p.nombre}}</option></select></div><div class="field"><label>Color</label><select v-if="colors(l).length" v-model="l.color"><option value="">Sin especificar</option><option v-for="c in colors(l)" :key="c">{{c}}</option></select><input v-else value="Sin variantes" disabled></div><div class="field"><label>Metros m²</label><input v-model.number="l.cantidadM2" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Contado / m² (USD)</label><input v-model.number="l.precioContadoM2" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Financiado / m² (USD)</label><input v-model.number="l.precioFinanciadoM2" type="number" min="0.01" step="0.01" required></div><div class="field highlight-field"><label>Totales de línea</label><strong>Contado {{usd(l.cantidadM2*l.precioContadoM2)}}</strong><small>Financiado {{usd(l.cantidadM2*l.precioFinanciadoM2)}}</small></div><button type="button" class="icon-btn danger" title="Quitar producto" :disabled="form.lineas.length===1" @click="removeLine(i)"><Trash2/></button></div></div><div class="sale-products-total quote-subtotals"><span>Subtotal contado <strong>{{usd(subtotalContado)}}</strong></span><span>Subtotal financiado <strong>{{usd(subtotalFinanciado)}}</strong></span></div></section>
<section class="panel sale-step"><div class="panel-head"><h3>3. Opciones para el cliente</h3><small>El PDF siempre incluirá contado y financiado.</small></div><div class="quote-payment"><article class="quote-option"><h4>Contado</h4><div class="form-grid"><div class="field"><label>Descuento (%)</label><input v-model.number="form.descuentoContadoPorcentaje" type="number" min="0" max="100" step="0.01"></div><div class="field"><label>IVA (%)</label><input v-model.number="form.ivaContadoPorcentaje" type="number" min="0" step="0.01"></div></div><strong>{{usd(contado)}}</strong></article><article class="quote-option financed"><h4>Financiado</h4><div class="form-grid"><div class="field"><label>IVA (%)</label><input v-model.number="form.ivaFinanciadoPorcentaje" type="number" min="0" step="0.01"></div><div class="field"><label>Entrega sin IVA (USD)</label><input v-model.number="form.entregaFinanciada" type="number" min="0" step="0.01"><small>En el PDF figurará este monto + IVA 21%.</small></div></div><strong>{{usd(financiado)}}</strong><small>Entrega con IVA 21%: {{usd(entregaConIva)}} · Saldo a financiar: {{usd(saldoFinanciado)}}</small></article></div><div class="field quote-notes"><label>Observaciones y condiciones</label><textarea v-model="form.observaciones" rows="4" placeholder="Flete, instalación, garantía u otras aclaraciones"></textarea></div></section>
<div class="actions"><RouterLink class="btn secondary" to="/presupuestos">Cancelar</RouterLink><button class="btn" :disabled="saving">{{saving?'Guardando…':'Guardar presupuesto'}}</button></div></form><NuevoClienteModal v-if="showNewClient" @close="showNewClient=false" @created="clientCreated"/></section></template>
