<script setup lang="ts">
import{onMounted,ref}from'vue'
import{http}from'@/shared/api/httpClient'
import{formatCurrency as money}from'@/shared/formatters'
const items=ref<any[]>([]),loading=ref(false),loadError=ref(''),desde=ref(''),hasta=ref(''),page=ref(1),totalPages=ref(0),total=ref(0)
async function load(reset=false){if(reset)page.value=1;loading.value=true;loadError.value='';try{const{data}=await http.get('/rentabilidad',{params:{desde:desde.value||undefined,hasta:hasta.value||undefined,page:page.value,pageSize:50}});items.value=data.items;total.value=data.total;totalPages.value=data.totalPages}catch(e:any){loadError.value=e?.response?.data?.errors?.hasta?.[0]||'No se pudo cargar el reporte de rentabilidad.'}finally{loading.value=false}}
function changePage(value:number){page.value=value;load()}
onMounted(()=>load())
</script>
<template><section class="page"><div class="page-title"><div><h2>Rentabilidad</h2><p>Precio − costos operativos − IVA = ganancia neta.</p></div></div><div class="formula card"><span>Precio de venta</span><b>−</b><span>Compra + envío + otros</span><b>−</b><span>IVA aplicado</span><b>=</b><strong>Ganancia neta</strong></div><form class="panel filters" @submit.prevent="load(true)"><div class="field"><label>Desde</label><input v-model="desde" type="date"></div><div class="field"><label>Hasta</label><input v-model="hasta" type="date"></div><button class="btn" :disabled="loading">Aplicar filtros</button><button type="button" class="btn secondary" @click="desde='';hasta='';load(true)">Limpiar</button></form><div v-if="loadError" class="error load-state">{{loadError}} <button class="btn secondary compact" @click="load()">Reintentar</button></div><div v-else class="panel"><div class="panel-head"><h3>{{total}} ventas encontradas</h3></div><div v-if="loading" class="loading">Cargando reporte…</div><table v-else><thead><tr><th>Fecha</th><th>Cliente</th><th>Venta</th><th>Costo operativo</th><th>IVA</th><th>Costo total</th><th>Ganancia bruta</th><th>Ganancia neta</th><th>Margen</th><th>Pendiente</th><th>Estado</th></tr></thead><tbody><tr v-for="r in items" :key="r.id"><td>{{r.fechaVenta}}</td><td><b>{{r.cliente}}</b></td><td>{{money(r.precioTotal)}}</td><td>{{money(r.costoOperativo)}}</td><td>{{money(r.iva)}}</td><td>{{money(r.costoTotal)}}</td><td>{{money(r.gananciaBruta)}}</td><td><b :class="{negative:r.gananciaNeta<0}">{{money(r.gananciaNeta)}}</b></td><td>{{(r.margen*100).toFixed(2)}}%</td><td>{{money(r.totalPendiente)}}</td><td><span class="badge">{{r.estadoFinanciero}}</span></td></tr></tbody></table><div v-if="!loading&&!items.length" class="empty">No hay ventas para el período seleccionado.</div><div v-if="totalPages>1" class="actions"><button class="btn secondary" :disabled="page<=1||loading" @click="changePage(page-1)">Anterior</button><span>Página {{page}} de {{totalPages}}</span><button class="btn secondary" :disabled="page>=totalPages||loading" @click="changePage(page+1)">Siguiente</button></div></div></section></template>
