using Api.Shared.Database;
using Microsoft.EntityFrameworkCore;
namespace Api.Features.Cuotas;
public record PagoRequest(decimal Importe,string MedioPago,DateOnly FechaPago);
public static class CuotaEndpoints
{
 public static void MapCuotaEndpoints(this IEndpointRouteBuilder app){var g=app.MapGroup("/api/cuotas").WithTags("Cuotas");g.MapGet("/pendientes",(AppDbContext db,CancellationToken ct)=>List(db,false,ct));g.MapGet("/abonadas",(AppDbContext db,CancellationToken ct)=>List(db,true,ct));g.MapPost("/{id:guid}/pagos",RegistrarPago);}
 static async Task<IResult> List(AppDbContext db,bool abonadas,CancellationToken ct){var q=db.Cuotas.AsNoTracking().Include(x=>x.Venta).ThenInclude(x=>x.Cliente).Include(x=>x.Venta).ThenInclude(x=>x.TipoCesped).Where(x=>abonadas?x.ImportePagado>=x.ImportePactado:x.ImportePagado<x.ImportePactado);var rows=await q.OrderByDescending(x=>abonadas?x.FechaPago:null).ThenBy(x=>x.FechaVencimiento).Select(x=>new{x.Id,x.VentaId,cliente=x.Venta.Cliente.Nombre+" "+x.Venta.Cliente.Apellido,fechaVenta=x.Venta.FechaVenta,tipoCesped=x.Venta.TipoCesped.Nombre,totalVenta=x.Venta.PrecioTotal,x.Numero,x.FechaVencimiento,x.FechaPago,fechaImpacto=x.UpdatedAt??x.CreatedAt,x.MedioPago,x.ImportePactado,x.ImportePagado,estado=abonadas?EstadoCuota.Pagada:x.FechaVencimiento<DateOnly.FromDateTime(DateTime.Today)&&x.Estado!=EstadoCuota.Pagada?EstadoCuota.Vencida:x.Estado}).ToListAsync(ct);return Results.Ok(rows);}
 static async Task<IResult> RegistrarPago(Guid id,PagoRequest r,AppDbContext db,CancellationToken ct){if(r.Importe<=0)return Results.ValidationProblem(new Dictionary<string,string[]>{{"importe",["El importe debe ser mayor a cero."]}});var c=await db.Cuotas.FindAsync([id],ct);if(c is null)return Results.NotFound();c.ImportePagado+=r.Importe;c.FechaPago=r.FechaPago;c.MedioPago=r.MedioPago;c.Estado=c.ImportePagado>=c.ImportePactado?EstadoCuota.Pagada:EstadoCuota.PagadaParcial;db.MovimientosCaja.Add(new MovimientoCaja{Tipo=TipoMovimiento.Ingreso,Fecha=DateTimeOffset.UtcNow,Monto=r.Importe,Concepto=$"Pago cuota {c.Numero}",CuotaId=c.Id,VentaId=c.VentaId});await db.SaveChangesAsync(ct);return Results.Ok(new{c.Id,c.ImportePagado,c.Estado});}
}
