using System.Security.Claims;using System.Text.Json;using Api.Shared.Database;using Microsoft.AspNetCore.Authentication;using Microsoft.AspNetCore.Authentication.Cookies;using Microsoft.AspNetCore.Identity;using Microsoft.EntityFrameworkCore;
namespace Api.Features.Auth;
public record LoginRequest(string Usuario,string Password);public record UsuarioRequest(string Nombre,string NombreUsuario,string? Password,string Rol,string[] Permisos,bool Activo);
public static class AuthEndpoints{
 public static void MapAuthEndpoints(this IEndpointRouteBuilder app){var a=app.MapGroup("/api/auth").WithTags("Auth");a.MapPost("/login",Login).AllowAnonymous();a.MapPost("/logout",async(HttpContext c)=>{await c.SignOutAsync();return Results.NoContent();});a.MapGet("/me",(ClaimsPrincipal u)=>Results.Ok(Current(u)));var g=app.MapGroup("/api/usuarios").WithTags("Usuarios").RequireAuthorization("Administrador");g.MapGet("/",List);g.MapPost("/",Create);g.MapPut("/{id:guid}",Update);g.MapDelete("/{id:guid}",Delete);}
 static object Current(ClaimsPrincipal u)=>new{id=u.FindFirstValue(ClaimTypes.NameIdentifier),nombre=u.Identity?.Name,usuario=u.FindFirstValue("usuario"),rol=u.FindFirstValue(ClaimTypes.Role),permisos=u.FindAll("permiso").Select(x=>x.Value)};
 static async Task<IResult> Login(LoginRequest r,AppDbContext db,IPasswordHasher<Usuario> h,HttpContext ctx,CancellationToken ct){var u=await db.Usuarios.SingleOrDefaultAsync(x=>x.NombreUsuario==r.Usuario&&x.Activo,ct);if(u is null||h.VerifyHashedPassword(u,u.PasswordHash,r.Password)==PasswordVerificationResult.Failed)return Results.Problem(statusCode:401,title:"Usuario o contraseña incorrectos");var permisos=u.Rol=="Administrador"?Permissions.All:JsonSerializer.Deserialize<string[]>(u.PermisosJson)??[];var claims=new List<Claim>{new(ClaimTypes.NameIdentifier,u.Id.ToString()),new(ClaimTypes.Name,u.Nombre),new("usuario",u.NombreUsuario),new(ClaimTypes.Role,u.Rol)};claims.AddRange(permisos.Select(x=>new Claim("permiso",x)));await ctx.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme)),new AuthenticationProperties{IsPersistent=true,ExpiresUtc=DateTimeOffset.UtcNow.AddHours(12)});return Results.Ok(Current(ctx.User=new ClaimsPrincipal(new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme))));}
 static async Task<IResult> List(AppDbContext db,CancellationToken ct){var usuarios=await db.Usuarios.AsNoTracking().OrderBy(x=>x.Nombre).ToListAsync(ct);return Results.Ok(usuarios.Select(x=>new{x.Id,x.Nombre,x.NombreUsuario,x.Rol,permisos=JsonSerializer.Deserialize<string[]>(x.PermisosJson)??[],x.Activo}));}
 static IResult Validate(UsuarioRequest r){if(string.IsNullOrWhiteSpace(r.Nombre)||string.IsNullOrWhiteSpace(r.NombreUsuario))return Results.ValidationProblem(new Dictionary<string,string[]>{{"usuario",["Nombre y usuario son obligatorios."]}});return Results.Ok();}
 static async Task<IResult> Create(UsuarioRequest r,AppDbContext db,IPasswordHasher<Usuario> h,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Password)||r.Password.Length<8)return Results.ValidationProblem(new Dictionary<string,string[]>{{"password",["La contraseña debe tener al menos 8 caracteres."]}});if(await db.Usuarios.AnyAsync(x=>x.NombreUsuario==r.NombreUsuario,ct))return Results.Conflict(new{message="El usuario ya existe."});var u=new Usuario{Nombre=r.Nombre.Trim(),NombreUsuario=r.NombreUsuario.Trim(),Rol=r.Rol,PermisosJson=JsonSerializer.Serialize(r.Permisos),Activo=r.Activo};u.PasswordHash=h.HashPassword(u,r.Password);db.Add(u);await db.SaveChangesAsync(ct);return Results.Created($"/api/usuarios/{u.Id}",new{u.Id});}
 static async Task<IResult> Update(Guid id,UsuarioRequest r,AppDbContext db,IPasswordHasher<Usuario> h,CancellationToken ct){var u=await db.Usuarios.FindAsync([id],ct);if(u is null)return Results.NotFound();if(await db.Usuarios.AnyAsync(x=>x.Id!=id&&x.NombreUsuario==r.NombreUsuario,ct))return Results.Conflict(new{message="El usuario ya existe."});u.Nombre=r.Nombre.Trim();u.NombreUsuario=r.NombreUsuario.Trim();u.Rol=r.Rol;u.PermisosJson=JsonSerializer.Serialize(r.Permisos);u.Activo=r.Activo;if(!string.IsNullOrWhiteSpace(r.Password)){if(r.Password.Length<8)return Results.BadRequest(new{message="La contraseña debe tener al menos 8 caracteres."});u.PasswordHash=h.HashPassword(u,r.Password);}await db.SaveChangesAsync(ct);return Results.NoContent();}
 static async Task<IResult> Delete(Guid id,ClaimsPrincipal current,AppDbContext db,CancellationToken ct){if(current.FindFirstValue(ClaimTypes.NameIdentifier)==id.ToString())return Results.Conflict(new{message="No podés eliminar tu propio usuario."});var u=await db.Usuarios.FindAsync([id],ct);if(u is null)return Results.NotFound();db.Remove(u);await db.SaveChangesAsync(ct);return Results.NoContent();}
}
public static class Permissions{public static readonly string[] All=["dashboard","ventas","entregas","clientes","cuotas","caja","rentabilidad","administracion","usuarios"];}
