USE [CespedVentas];
GO
IF OBJECT_ID(N'dbo.Usuarios',N'U') IS NULL CREATE TABLE dbo.Usuarios(Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Usuarios_Id DEFAULT NEWSEQUENTIALID(),Nombre NVARCHAR(150) NOT NULL,NombreUsuario NVARCHAR(100) NOT NULL,PasswordHash NVARCHAR(1000) NOT NULL,Rol NVARCHAR(30) NOT NULL,PermisosJson NVARCHAR(MAX) NOT NULL CONSTRAINT DF_Usuarios_Permisos DEFAULT N'[]',Activo BIT NOT NULL CONSTRAINT DF_Usuarios_Activo DEFAULT 1,CreatedAt DATETIMEOFFSET(7) NOT NULL CONSTRAINT DF_Usuarios_CreatedAt DEFAULT SYSDATETIMEOFFSET(),UpdatedAt DATETIMEOFFSET(7) NULL,CONSTRAINT PK_Usuarios PRIMARY KEY(Id),CONSTRAINT UQ_Usuarios_NombreUsuario UNIQUE(NombreUsuario));
GO
