<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { http, apiErrorMessage } from '@/shared/api/httpClient'
import GeografiaAutocomplete from './GeografiaAutocomplete.vue'

interface GeoOption{id:string;nombre:string}
const emit=defineEmits<{(e:'close'):void;(e:'created',cliente:any):void}>()
const provincias=ref<GeoOption[]>([]),localidades=ref<GeoOption[]>([]),geoAvailable=ref(false),geoMode=ref(false),geoLoading=ref(false)
const saving=ref(false),error=ref(''),geoNotice=ref('')
const fields=[{key:'nombre',label:'Nombre',type:'text'},{key:'apellido',label:'Apellido',type:'text'},{key:'telefono',label:'Teléfono',type:'tel'},{key:'correo',label:'Correo electrónico',type:'email'}] as const
const form=ref({nombre:'',apellido:'',telefono:'',correo:'',localidad:'',provincia:'',localidadId:'',provinciaId:'',tipo:'Particular',fechaPrimerContacto:new Date().toISOString().slice(0,10),observaciones:''})

async function loadProvincias(){try{provincias.value=(await http.get('/geografia/provincias')).data;geoAvailable.value=true;geoMode.value=true}catch{geoAvailable.value=false;geoMode.value=false;geoNotice.value='Georef no está disponible. Podés cargar la ubicación manualmente.'}}
async function loadLocalidades(){localidades.value=[];if(!form.value.provinciaId)return;geoLoading.value=true;try{localidades.value=(await http.get('/geografia/localidades',{params:{provincia:form.value.provinciaId}})).data}catch{useManual();geoNotice.value='Georef no respondió. Se habilitó la carga manual.'}finally{geoLoading.value=false}}
async function provinceChanged(){const option=provincias.value.find(x=>x.id===form.value.provinciaId);form.value.provincia=option?.nombre??'';form.value.localidad='';form.value.localidadId='';await loadLocalidades()}
function localitySelected(option:GeoOption){form.value.localidad=option.nombre}
function useManual(){geoMode.value=false;form.value.provinciaId='';form.value.localidadId='';localidades.value=[];geoNotice.value='Ubicación en modo manual: se guardarán los nombres sin códigos oficiales.'}
function enableOfficial(){geoMode.value=true;geoNotice.value='';form.value.provincia='';form.value.localidad='';form.value.provinciaId='';form.value.localidadId='';localidades.value=[]}
function message(e:any){const first=Object.values(e.response?.data?.errors??{}).flat()[0];return first?String(first):apiErrorMessage(e,'No se pudo guardar el cliente.')}
async function save(){error.value='';if(geoMode.value&&(!form.value.provinciaId||!form.value.localidadId)){error.value='Seleccioná una provincia y una localidad de las opciones oficiales.';return}saving.value=true;try{const {data}=await http.post('/clientes',form.value);emit('created',data)}catch(e:any){error.value=message(e)}finally{saving.value=false}}
onMounted(loadProvincias)
</script>

<template><div class="modal-bg"><form class="modal" @submit.prevent="save"><h3>Nuevo cliente</h3><p>Se guardará y quedará seleccionado en esta venta.</p><p v-if="error" class="error">{{error}}</p><p v-if="geoNotice" class="load-state">{{geoNotice}}</p><div class="form-grid"><div v-for="field in fields" :key="field.key" class="field"><label>{{field.label}}</label><input v-model="(form as any)[field.key]" :type="field.type" :required="field.key!=='correo'" :maxlength="field.key==='telefono'?30:field.key==='correo'?200:100" :pattern="field.key==='telefono'?'\\+?[0-9 ()-]{6,30}':undefined"></div><template v-if="geoMode"><div class="field full-field"><span class="badge">Ubicación oficial de Argentina</span></div><div class="field"><label>País</label><input value="Argentina" readonly></div><div class="field"><label>Provincia</label><select v-model="form.provinciaId" required @change="provinceChanged"><option value="">Seleccionar provincia</option><option v-for="p in provincias" :key="p.id" :value="p.id">{{p.nombre}}</option></select></div><div class="field"><label>Localidad</label><GeografiaAutocomplete v-model="form.localidadId" :options="localidades" :disabled="!form.provinciaId||geoLoading" :placeholder="geoLoading?'Cargando localidades…':'Buscar localidad'" @select="localitySelected"/></div><div class="field"><label>Origen</label><button type="button" class="btn secondary" @click="useManual">Cargar manualmente</button></div></template><template v-else><div class="field full-field"><span class="badge warn">Modo manual: la ubicación se guardará sin códigos oficiales.</span></div><div class="field"><label>Provincia</label><input v-model="form.provincia" maxlength="100" required></div><div class="field"><label>Localidad</label><input v-model="form.localidad" maxlength="100" required></div><div v-if="geoAvailable" class="field full-field"><button type="button" class="btn secondary" @click="enableOfficial">Usar ubicaciones oficiales de Argentina</button></div></template><div class="field"><label>Tipo</label><select v-model="form.tipo"><option v-for="t in ['Particular','Club','Empresa','Constructor','Revendedor','Otro']" :key="t">{{t}}</option></select></div><div class="field"><label>Primer contacto</label><input v-model="form.fechaPrimerContacto" type="date" required></div><div class="field full-field"><label>Observaciones</label><textarea v-model="form.observaciones" maxlength="1000" rows="3"></textarea></div></div><div class="actions"><button type="button" class="btn secondary" @click="emit('close')">Cancelar</button><button class="btn" :disabled="saving">{{saving?'Guardando…':'Guardar cliente'}}</button></div></form></div></template>
